# Generated by Django 3.1.3 on 2020-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='avatar.png', upload_to='profile_pictures/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
