# Generated by Django 3.1.3 on 2020-12-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201204_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
